<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Abp.Interception.Castle</AssemblyName>
    <PackageId>Abp.Interception.Castle</PackageId>
    <RootNamespace>Abp.Interception.Castle</RootNamespace>
    <Description>Castle DynamicProxy interception support for ASP.NET Boilerplate.</Description>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Abp.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abp\Abp.csproj" />
  </ItemGroup>

</Project>
