using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Abp.SourceGenerators;

internal static class InterceptorEmitter
{
    public static string? Emit(Compilation compilation, string? assemblyName, ConventionTypeModel model)
    {
        if (!model.IsApplicationService || model.Methods.IsEmpty)
        {
            return null;
        }

        var ns = GeneratedNamespace.Get(assemblyName);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {ns};");
        builder.AppendLine();
        builder.AppendLine("file sealed class InterceptsLocationAttribute : System.Attribute");
        builder.AppendLine("{");
        builder.AppendLine("    public InterceptsLocationAttribute(int version, string data) { }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"[global::Abp.Dependency.CompileTime.DisableConventionalRegistration]");
        builder.AppendLine($"internal sealed class {model.InterceptedTypeName} : {GetPrimaryInterface(model)}, global::Abp.Dependency.ITransientDependency, global::Abp.Application.Services.IAvoidDuplicateCrossCuttingConcerns");
        builder.AppendLine("{");
        builder.AppendLine("    public global::System.Collections.Generic.List<string> AppliedCrossCuttingConcerns { get; } = new();");
        builder.AppendLine($"    private readonly {model.ImplementationTypeName} _inner;");
        builder.AppendLine("    private readonly global::Abp.Dependency.CompileTime.CompileTimeAspectExecutor _aspects;");
        builder.AppendLine();
        builder.AppendLine($"    public {model.InterceptedTypeName}(");
        builder.AppendLine($"        {model.ImplementationTypeName} inner,");
        builder.AppendLine("        global::Abp.Dependency.CompileTime.CompileTimeAspectExecutor aspects)");
        builder.AppendLine("    {");
        builder.AppendLine("        _inner = inner;");
        builder.AppendLine("        _aspects = aspects;");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var method in model.Methods)
        {
            EmitDecoratorMethod(builder, model, method);
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"file static class {model.RelayClassName}");
        builder.AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitRelayMethods(compilation, builder, model, method);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string GetPrimaryInterface(ConventionTypeModel model)
    {
        return model.ServiceInterfaces.FirstOrDefault(i => i.Contains("AppService"))
               ?? model.ServiceInterfaces.First();
    }

    private static void EmitDecoratorMethod(StringBuilder builder, ConventionTypeModel model, MethodModel method)
    {
        builder.AppendLine($"    public {method.ReturnType} {method.Signature}");
        builder.AppendLine("    {");
        builder.AppendLine($"        return {model.RelayClassName}.{method.Name}(_inner, _aspects{(method.ParameterList.Length > 0 ? ", " : "")}{method.ArgumentList});");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitRelayMethods(Compilation compilation, StringBuilder builder, ConventionTypeModel model, MethodModel method)
    {
        var relayParameters = $"{model.ImplementationTypeName} inner, global::Abp.Dependency.CompileTime.CompileTimeAspectExecutor aspects"
                              + (method.ParameterList.Length > 0 ? ", " + method.ParameterList : string.Empty);

        var relayBody = method.ParameterList.Length == 0
            ? $"inner.{method.Name}()"
            : $"inner.{method.Name}({method.ArgumentList})";

        var interceptAttribute = TryGetInterceptAttribute(compilation, model, method, relayBody);
        if (interceptAttribute == null)
        {
            EmitInlineRelay(builder, model, method, relayParameters, relayBody);
            return;
        }

        var optionsBlock = BuildOptionsBlock(model, method);
        var accessorName = $"{method.Name}_Original";
        var originalCall = method.ParameterList.Length == 0
            ? $"{accessorName}(inner)"
            : $"{accessorName}(inner, {method.ArgumentList})";

        builder.AppendLine($"    public static {method.ReturnType} {method.Name}({relayParameters})");
        builder.AppendLine("    {");
        EmitValidation(builder, method);
        builder.AppendLine($"        using (global::Abp.Dependency.CompileTime.CompileTimeInterceptorContext.Enter(aspects, {optionsBlock}))");
        builder.AppendLine("        {");
        builder.AppendLine($"            return {relayBody};");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();

        var interceptedParameters = method.ParameterList.Length == 0
            ? $"{model.ImplementationTypeName} inner"
            : $"{model.ImplementationTypeName} inner, {method.ParameterList}";

        builder.AppendLine($"    [{interceptAttribute}]");
        builder.AppendLine($"    public static {method.ReturnType} {method.Name}_Intercepted({interceptedParameters})");
        builder.AppendLine("    {");
        builder.AppendLine("        var scope = global::Abp.Dependency.CompileTime.CompileTimeInterceptorContext.Current");
        builder.AppendLine("            ?? throw new global::System.InvalidOperationException(\"Compile-time interceptor scope is missing.\");");
        builder.AppendLine();

        if (method.IsAsync)
        {
            if (method.ReturnType.StartsWith("System.Threading.Tasks.Task<"))
            {
                builder.AppendLine($"        return scope.Executor.InvokeAsync(() => {originalCall}, scope.Options);");
            }
            else
            {
                builder.AppendLine($"        return scope.Executor.InvokeAsync(async () => {{ {originalCall}; }}, scope.Options);");
            }
        }
        else if (method.ReturnType == "void")
        {
            builder.AppendLine($"        scope.Executor.Invoke(() => {{ {originalCall}; }}, scope.Options);");
        }
        else
        {
            builder.AppendLine($"        return scope.Executor.Invoke(() => {originalCall}, scope.Options);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        EmitUnsafeAccessor(builder, model, method, accessorName);
        builder.AppendLine();
    }

    private static void EmitInlineRelay(StringBuilder builder, ConventionTypeModel model, MethodModel method, string relayParameters, string relayBody)
    {
        builder.AppendLine($"    public static {method.ReturnType} {method.Name}({relayParameters})");
        builder.AppendLine("    {");
        EmitValidation(builder, method);

        builder.AppendLine($"        var options = {BuildOptionsBlock(model, method)};");

        if (method.IsAsync)
        {
            if (method.ReturnType.StartsWith("System.Threading.Tasks.Task<"))
            {
                builder.AppendLine($"        return aspects.InvokeAsync(() => {relayBody}, options);");
            }
            else
            {
                builder.AppendLine($"        return aspects.InvokeAsync(async () => {{ {relayBody}; }}, options);");
            }
        }
        else if (method.ReturnType == "void")
        {
            builder.AppendLine($"        aspects.Invoke(() => {{ {relayBody}; }}, options);");
        }
        else
        {
            builder.AppendLine($"        return aspects.Invoke(() => {relayBody}, options);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitValidation(StringBuilder builder, MethodModel method)
    {
        if (method.Validate && method.ParameterList.Length > 0)
        {
            builder.AppendLine($"        global::Abp.Dependency.CompileTime.CompileTimeDtoValidator.ValidateArguments({method.ArgumentList});");
        }
    }

    private static string BuildOptionsBlock(ConventionTypeModel model, MethodModel method)
    {
        var builder = new StringBuilder();
        builder.AppendLine("new global::Abp.Dependency.CompileTime.CompileTimeMethodAspectOptions");
        builder.AppendLine("        {");
        builder.AppendLine($"            ServiceName = \"{model.ImplementationTypeName}\",");
        builder.AppendLine($"            MethodName = \"{method.Name}\",");
        builder.AppendLine($"            Audit = {method.Aspect.Audit.ToString().ToLowerInvariant()},");
        builder.AppendLine($"            Validate = false,");
        builder.AppendLine($"            AllowAnonymous = {method.Aspect.AllowAnonymous.ToString().ToLowerInvariant()},");

        if (method.Aspect.UnitOfWorkOptionsExpression != null)
        {
            builder.AppendLine($"            UnitOfWork = {method.Aspect.UnitOfWorkOptionsExpression},");
        }

        if (method.Aspect.AuthorizeAttributesExpression != null)
        {
            builder.AppendLine($"            AuthorizeAttributes = {method.Aspect.AuthorizeAttributesExpression},");
        }

        if (method.Aspect.FeatureAttributesExpression != null)
        {
            builder.AppendLine($"            FeatureAttributes = {method.Aspect.FeatureAttributesExpression},");
        }

        builder.AppendLine($"            AuditParameters = {method.Aspect.AuditParametersExpression}");
        builder.Append("        }");
        return builder.ToString();
    }

    private static void EmitUnsafeAccessor(StringBuilder builder, ConventionTypeModel model, MethodModel method, string accessorName)
    {
        var parameters = method.ParameterList.Length == 0
            ? $"{model.ImplementationTypeName} @this"
            : $"{model.ImplementationTypeName} @this, {method.ParameterList}";

        builder.AppendLine($"    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"{method.Name}\")]");
        builder.AppendLine($"    private static extern {method.ReturnType} {accessorName}({parameters});");
    }

    private static string? TryGetInterceptAttribute(Compilation compilation, ConventionTypeModel model, MethodModel method, string relayBody)
    {
        try
        {
            var generatedNs = GeneratedNamespace.Get(compilation.AssemblyName);
            var relayParameters = $"{model.ImplementationTypeName} inner, global::Abp.Dependency.CompileTime.CompileTimeAspectExecutor aspects"
                                  + (method.ParameterList.Length > 0 ? ", " + method.ParameterList : string.Empty);

            var relaySource = $@"#nullable enable
namespace {generatedNs};
file static class {model.RelayClassName}
{{
    public static {method.ReturnType} {method.Name}({relayParameters})
        => {relayBody};
}}";

            var parseOptions = (compilation.SyntaxTrees.FirstOrDefault()?.Options as CSharpParseOptions) ?? new CSharpParseOptions();
            var tree = CSharpSyntaxTree.ParseText(relaySource, parseOptions);
            var tmpCompilation = compilation.AddSyntaxTrees(tree);
            var semanticModel = tmpCompilation.GetSemanticModel(tree);
            var invocation = tree.GetRoot()
                .DescendantNodes()
                .OfType<InvocationExpressionSyntax>()
                .FirstOrDefault();

            if (invocation == null)
            {
                return null;
            }

            var location = semanticModel.GetInterceptableLocation(invocation, default);
            if (location == null)
            {
                return null;
            }

            return $"InterceptsLocation({location.Version}, \"{location.Data}\")";
        }
        catch
        {
            return null;
        }
    }
}
