using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Abp.SourceGenerators;

internal static class InterceptorEmitter
{
    public static string? Emit(Compilation compilation, string? assemblyName, ConventionTypeModel model)
    {
        if (!model.RequiresCompileTimeInterception || model.Methods.IsEmpty)
        {
            return null;
        }

        var userInterceptors = UserInterceptorRegistry.Collect(compilation).AllInterceptors;
        var serviceInterceptors = AspectAnalyzer.CollectServiceInterceptorFields(model, userInterceptors);
        var ns = GeneratedNamespace.Get(assemblyName);
        var avoidDuplicateConcerns = model.IsApplicationService
            ? $", {AbpTypeNames.FullyQualified.IAvoidDuplicateCrossCuttingConcerns}"
            : string.Empty;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {ns};");
        builder.AppendLine();
        builder.AppendLine($"[{AbpTypeNames.FullyQualified.DisableConventionalRegistrationAttribute}]");
        builder.AppendLine($"internal sealed class {model.InterceptedTypeName} : {GetPrimaryInterface(model)}, {AbpTypeNames.FullyQualified.ITransientDependency}{avoidDuplicateConcerns}");
        builder.AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitMethodInfoField(builder, model, method);
            if (method.AbpReflection)
            {
                EmitMetadataField(builder, method);
            }
        }

        var abpReflectionMethods = model.Methods.Where(m => m.AbpReflection).ToImmutableArray();
        if (!abpReflectionMethods.IsEmpty)
        {
            builder.AppendLine($"    static {model.InterceptedTypeName}()");
            builder.AppendLine("    {");
            foreach (var method in abpReflectionMethods)
            {
                EmitMetadataRegistration(builder, method);
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        if (model.IsApplicationService)
        {
            builder.AppendLine("    public global::System.Collections.Generic.List<string> AppliedCrossCuttingConcerns { get; } = new();");
        }

        builder.AppendLine($"    private readonly {model.ImplementationTypeName} _inner;");

        if (!serviceInterceptors.IsDefaultOrEmpty)
        {
            builder.AppendLine($"    private readonly {AbpTypeNames.FullyQualified.IIocResolver} _iocResolver;");
        }

        foreach (var interceptor in serviceInterceptors)
        {
            builder.AppendLine($"    private readonly {AbpTypeNames.FullyQualified.AbpInterceptorBase} {interceptor.FieldName};");
        }

        builder.AppendLine();
        builder.AppendLine($"    public {model.InterceptedTypeName}(");
        builder.AppendLine($"        {model.ImplementationTypeName} inner");

        if (!serviceInterceptors.IsDefaultOrEmpty)
        {
            builder.AppendLine($"        , {AbpTypeNames.FullyQualified.IIocResolver} iocResolver");
        }

        builder.AppendLine("    )");
        builder.AppendLine("    {");
        builder.AppendLine("        _inner = inner;");

        if (!serviceInterceptors.IsDefaultOrEmpty)
        {
            builder.AppendLine("        _iocResolver = iocResolver;");
        }

        foreach (var interceptor in serviceInterceptors)
        {
            builder.AppendLine($"        {interceptor.FieldName} = {interceptor.ResolveExpression};");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var method in model.Methods)
        {
            EmitInterceptedMethod(builder, model, method, serviceInterceptors, userInterceptors);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string GetPrimaryInterface(ConventionTypeModel model)
    {
        if (model.ServiceInterfaces.IsDefaultOrEmpty)
        {
            return model.ImplementationTypeName;
        }

        return model.ServiceInterfaces.FirstOrDefault(i => i.Contains("AppService"))
               ?? model.ServiceInterfaces.First();
    }

    private static void EmitInterceptedMethod(
        StringBuilder builder,
        ConventionTypeModel model,
        MethodModel method,
        ImmutableArray<BakedInterceptorField> serviceInterceptors,
        ImmutableArray<BakedInterceptorField> userInterceptors)
    {
        var innerCallExpression = method.ParameterList.Length == 0
            ? $"_inner.{method.Name}()"
            : $"_inner.{method.Name}({method.ArgumentList})";

        var useValueTaskMethod = method.IsAsync && IsValueTaskReturnType(method.ReturnType);
        var useTaskStructMethod = method.IsAsync && IsTaskReturnType(method.ReturnType);
        builder.AppendLine($"    public {method.ReturnType} {method.Signature}");
        builder.AppendLine("    {");

        if (useValueTaskMethod)
        {
            EmitAsyncInvocationSetup(builder, method, isTask: false);
        }
        else if (useTaskStructMethod)
        {
            EmitAsyncInvocationSetup(builder, method, isTask: true);
        }
        else if (!method.IsAsync)
        {
            EmitAbpInvocationStructSetup(builder, method);
        }

        EmitLinearInterceptorChain(
            builder,
            method,
            innerCallExpression,
            AspectAnalyzer.GetMethodInterceptorFields(method.Aspect, model.IsApplicationService, userInterceptors),
            useValueTaskMethod,
            useTaskStructMethod);
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitAbpInvocationStructSetup(StringBuilder builder, MethodModel method)
    {
        var argumentsExpression = method.ArgumentList.Length == 0
            ? "global::System.Array.Empty<object?>()"
            : $"new object?[] {{ {method.ArgumentList} }}";

        var invocationMethodExpression = GetInvocationMethodExpression(method);
        builder.AppendLine($"        var invocation = default({AbpTypeNames.FullyQualified.AbpInvocationStruct});");
        builder.AppendLine($"        invocation.Initialize(_inner, {invocationMethodExpression}, {argumentsExpression});");
    }

    private static void EmitAsyncInvocationSetup(StringBuilder builder, MethodModel method, bool isTask)
    {
        var argumentsExpression = method.ArgumentList.Length == 0
            ? "global::System.Array.Empty<object?>()"
            : $"new object?[] {{ {method.ArgumentList} }}";

        var invocationType = GetAsyncInvocationTypeName(method, isTask);
        var invocationMethodExpression = GetInvocationMethodExpression(method);
        builder.AppendLine($"        var invocation = default({invocationType});");
        builder.AppendLine($"        invocation.Initialize(_inner, {invocationMethodExpression}, {argumentsExpression});");
        builder.AppendLine($"        {GetAsyncClassBridgeTypeName(method)} classBridge = null;");
    }

    private static string GetAsyncClassBridgeTypeName(MethodModel method)
    {
        if (IsGenericAsyncReturnType(method.ReturnType, out var resultType))
        {
            return $"{AbpTypeNames.FullyQualified.AbpInvocationCompileTime}<{resultType}>?";
        }

        return $"{AbpTypeNames.FullyQualified.AbpInvocationCompileTime}?";
    }

    private static void EmitLinearInterceptorChain(
        StringBuilder builder,
        MethodModel method,
        string innerCallExpression,
        ImmutableArray<BakedInterceptorField> interceptors,
        bool useValueTaskMethod,
        bool useTaskStructMethod)
    {
        if (interceptors.IsDefaultOrEmpty)
        {
            if (method.ReturnType == "void")
            {
                builder.AppendLine($"        {innerCallExpression};");
                return;
            }

            builder.AppendLine($"        return {innerCallExpression};");
            return;
        }

        var executor = AbpTypeNames.FullyQualified.CompileTimeInvocationInterceptorExecutor;

        if (useValueTaskMethod)
        {
            EmitMultilineValueTaskLayerChain(builder, executor, method, interceptors, innerCallExpression);
            return;
        }

        if (!method.IsAsync)
        {
            EmitMultilineSyncLayerChain(builder, executor, method, interceptors, innerCallExpression);

            if (method.ReturnType == "void")
            {
                return;
            }

            builder.AppendLine($"        return ({method.ReturnType})invocation.ReturnValue!;");
            return;
        }

        if (useTaskStructMethod)
        {
            EmitMultilineTaskLayerChain(builder, executor, method, interceptors, innerCallExpression);
        }
    }

    private static string GetIndent(int depth) => new string(' ', 8 + depth * 4);

    private static void EmitMultilineSyncLayerChain(
        StringBuilder builder,
        string executor,
        MethodModel method,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression)
    {
        EmitSyncLayerChainRecursive(builder, executor, method, interceptors, innerCallExpression, index: 0, layerDepth: 0);
    }

    private static void EmitSyncLayerChainRecursive(
        StringBuilder builder,
        string executor,
        MethodModel method,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression,
        int index,
        int layerDepth)
    {
        var indent = GetIndent(layerDepth);
        var argIndent = GetIndent(layerDepth + 1);

        builder.AppendLine($"{indent}{executor}.{GetSyncExecutorMethod(interceptors[index])}(");
        builder.AppendLine($"{argIndent}ref invocation,");
        builder.AppendLine($"{argIndent}{GetSyncInterceptorExpression(interceptors[index])},");
        builder.AppendLine($"{argIndent}() =>");
        builder.AppendLine($"{argIndent}{{");

        if (index == interceptors.Length - 1)
        {
            EmitSyncInnermostBody(builder, method, innerCallExpression, layerDepth + 2);
            builder.AppendLine($"{argIndent}}});");
            return;
        }

        EmitSyncLayerChainRecursive(
            builder,
            executor,
            method,
            interceptors,
            innerCallExpression,
            index + 1,
            layerDepth + 2);
        builder.AppendLine($"{GetIndent(layerDepth + 2)}return global::System.Threading.Tasks.Task.FromResult<object?>(invocation.ReturnValue);");
        builder.AppendLine($"{argIndent}}});");
    }

    private static void EmitSyncInnermostBody(
        StringBuilder builder,
        MethodModel method,
        string innerCallExpression,
        int depth)
    {
        var indent = GetIndent(depth);
        var taskFromResult = "global::System.Threading.Tasks.Task.FromResult<object?>";

        if (method.ReturnType == "void")
        {
            builder.AppendLine($"{indent}{innerCallExpression};");
            builder.AppendLine($"{indent}return {taskFromResult}(null);");
            return;
        }

        builder.AppendLine($"{indent}invocation.ReturnValue = {innerCallExpression};");
        builder.AppendLine($"{indent}return {taskFromResult}(invocation.ReturnValue);");
    }

    private static void EmitMultilineTaskLayerChain(
        StringBuilder builder,
        string executor,
        MethodModel method,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression)
    {
        var layerType = IsGenericAsyncReturnType(method.ReturnType, out var taskResultType)
            ? $"<{taskResultType}>"
            : string.Empty;

        EmitTaskLayerChainRecursive(
            builder,
            executor,
            layerType,
            interceptors,
            innerCallExpression,
            index: 0);
    }

    private static void EmitTaskLayerChainRecursive(
        StringBuilder builder,
        string executor,
        string layerType,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression,
        int index)
    {
        var layerMethod = GetTaskExecutorMethod(interceptors[index], layerType);
        if (index == 0)
        {
            builder.AppendLine($"{GetIndent(0)}return {executor}.{layerMethod}(");
        }
        else
        {
            builder.AppendLine($"{GetIndent(index)}() => {executor}.{layerMethod}(");
        }

        var argIndent = GetIndent(index + 1);

        builder.AppendLine($"{argIndent}ref invocation,");
        builder.AppendLine($"{argIndent}{GetTaskInterceptorExpression(interceptors[index])},");
        if (UsesClassBridgeParameterForTask(interceptors[index]))
        {
            builder.AppendLine($"{argIndent}ref classBridge,");
        }

        if (index == interceptors.Length - 1)
        {
            builder.AppendLine($"{argIndent}() => {innerCallExpression}");
            EmitValueTaskLayerClose(builder, index, isRoot: index == 0);
            return;
        }

        EmitTaskLayerChainRecursive(builder, executor, layerType, interceptors, innerCallExpression, index + 1);
        EmitValueTaskLayerClose(builder, index, isRoot: index == 0);
    }

    private static void EmitMultilineValueTaskLayerChain(
        StringBuilder builder,
        string executor,
        MethodModel method,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression)
    {
        var layerType = IsGenericAsyncReturnType(method.ReturnType, out var valueTaskResultType)
            ? $"<{valueTaskResultType}>"
            : string.Empty;

        EmitValueTaskLayerChainRecursive(
            builder,
            executor,
            layerType,
            interceptors,
            innerCallExpression,
            index: 0);
    }

    private static void EmitValueTaskLayerChainRecursive(
        StringBuilder builder,
        string executor,
        string layerType,
        ImmutableArray<BakedInterceptorField> interceptors,
        string innerCallExpression,
        int index)
    {
        var layerMethod = GetValueTaskExecutorMethod(interceptors[index], layerType);
        if (index == 0)
        {
            builder.AppendLine($"{GetIndent(0)}return {executor}.{layerMethod}(");
        }
        else
        {
            builder.AppendLine($"{GetIndent(index)}() => {executor}.{layerMethod}(");
        }

        var argIndent = GetIndent(index + 1);

        builder.AppendLine($"{argIndent}ref invocation,");
        builder.AppendLine($"{argIndent}{GetValueTaskInterceptorExpression(interceptors[index])},");
        if (UsesClassBridgeParameterForValueTask(interceptors[index]))
        {
            builder.AppendLine($"{argIndent}ref classBridge,");
        }

        if (index == interceptors.Length - 1)
        {
            builder.AppendLine($"{argIndent}() => {innerCallExpression}");
            EmitValueTaskLayerClose(builder, index, isRoot: index == 0);
            return;
        }

        EmitValueTaskLayerChainRecursive(builder, executor, layerType, interceptors, innerCallExpression, index + 1);
        EmitValueTaskLayerClose(builder, index, isRoot: index == 0);
    }

    private static bool UsesClassBridgeParameterForTask(BakedInterceptorField interceptor)
    {
        return interceptor.TaskLayerKind != TaskLayerKind.AllocationFreeTask;
    }

    private static string GetSyncExecutorMethod(BakedInterceptorField interceptor)
    {
        return interceptor.SyncLayerKind switch
        {
            SyncLayerKind.AllocationFreeSync => "RunSyncAllocationFreeLayer",
            _ => "RunSyncLayer",
        };
    }

    private static string GetSyncInterceptorExpression(BakedInterceptorField interceptor)
    {
        return interceptor.SyncLayerKind switch
        {
            SyncLayerKind.AllocationFreeSync =>
                $"({AbpTypeNames.FullyQualified.IAbpInterceptorSync}){interceptor.FieldName}",
            _ => interceptor.FieldName,
        };
    }

    private static bool UsesClassBridgeParameterForValueTask(BakedInterceptorField interceptor)
    {
        return interceptor.ValueTaskLayerKind == ValueTaskLayerKind.ClassBridge;
    }

    private static string GetTaskExecutorMethod(BakedInterceptorField interceptor, string layerType)
    {
        return interceptor.TaskLayerKind switch
        {
            TaskLayerKind.AllocationFreeTask => $"RunTaskAllocationFreeLayer{layerType}",
            _ => $"RunTaskViaClassBridgeLayer{layerType}",
        };
    }

    private static string GetTaskInterceptorExpression(BakedInterceptorField interceptor)
    {
        return interceptor.TaskLayerKind switch
        {
            TaskLayerKind.AllocationFreeTask =>
                $"({AbpTypeNames.FullyQualified.IAbpInterceptorTaskAsync}){interceptor.FieldName}",
            _ => interceptor.FieldName,
        };
    }

    private static string GetValueTaskExecutorMethod(BakedInterceptorField interceptor, string layerType)
    {
        return interceptor.ValueTaskLayerKind switch
        {
            ValueTaskLayerKind.AllocationFreeValueTask => $"RunValueTaskAllocationFreeLayer{layerType}",
            ValueTaskLayerKind.AllocationFreeTaskBridge => $"RunValueTaskViaTaskStructLayer{layerType}",
            _ => $"RunValueTaskViaClassBridgeLayer{layerType}",
        };
    }

    private static string GetValueTaskInterceptorExpression(BakedInterceptorField interceptor)
    {
        return interceptor.ValueTaskLayerKind switch
        {
            ValueTaskLayerKind.AllocationFreeValueTask =>
                $"({AbpTypeNames.FullyQualified.IAbpInterceptorValueTaskAsync}){interceptor.FieldName}",
            ValueTaskLayerKind.AllocationFreeTaskBridge =>
                $"({AbpTypeNames.FullyQualified.IAbpInterceptorTaskAsync}){interceptor.FieldName}",
            _ => interceptor.FieldName,
        };
    }

    private static void EmitValueTaskLayerClose(StringBuilder builder, int index, bool isRoot)
    {
        builder.AppendLine(isRoot ? $"{GetIndent(index)});" : $"{GetIndent(index)})");
    }

    private static string NormalizeTypeName(string returnType)
    {
        return returnType.StartsWith("global::", StringComparison.Ordinal)
            ? returnType.Substring("global::".Length)
            : returnType;
    }

    private static bool IsTaskReturnType(string returnType)
    {
        var normalized = NormalizeTypeName(returnType);
        return normalized == "System.Threading.Tasks.Task"
               || normalized.StartsWith("System.Threading.Tasks.Task<", StringComparison.Ordinal);
    }

    private static bool IsValueTaskReturnType(string returnType)
    {
        var normalized = NormalizeTypeName(returnType);
        return normalized == "System.Threading.Tasks.ValueTask"
               || normalized.StartsWith("System.Threading.Tasks.ValueTask<", StringComparison.Ordinal);
    }

    private static bool IsGenericAsyncReturnType(string returnType, out string resultType)
    {
        var normalized = NormalizeTypeName(returnType);

        if (normalized.StartsWith("System.Threading.Tasks.Task<", StringComparison.Ordinal))
        {
            resultType = normalized.Substring("System.Threading.Tasks.Task<".Length).TrimEnd('>');
            return true;
        }

        if (normalized.StartsWith("System.Threading.Tasks.ValueTask<", StringComparison.Ordinal))
        {
            resultType = normalized.Substring("System.Threading.Tasks.ValueTask<".Length).TrimEnd('>');
            return true;
        }

        resultType = string.Empty;
        return false;
    }

    private static void EmitMethodInfoField(StringBuilder builder, ConventionTypeModel model, MethodModel method)
    {
        var methodFieldName = GetMethodFieldName(method);
        var parameterTypes = EmitGetMethodParameterTypes(method);

        builder.AppendLine($"    private static readonly global::System.Reflection.MethodInfo {methodFieldName} = typeof({model.ImplementationTypeName}).GetMethod(");
        builder.AppendLine($"        {method.MethodNameExpression},");
        builder.AppendLine("        global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public,");
        builder.AppendLine("        binder: null,");
        builder.AppendLine($"        types: {parameterTypes},");
        builder.AppendLine("        modifiers: null)!;");
        builder.AppendLine();
    }

    private static void EmitMetadataField(StringBuilder builder, MethodModel method)
    {
        var aspect = method.Aspect;
        var authorize = aspect.AuthorizeAttributesExpression ?? "null";
        var features = aspect.FeatureAttributesExpression ?? "null";
        var unitOfWorkAttribute = aspect.UnitOfWorkAttributeExpression ?? "null";
        var metadataFieldName = GetMethodMetadataFieldName(method);

        builder.AppendLine($"    private static readonly {AbpTypeNames.FullyQualified.AbpMethodInterceptionMetadata} {metadataFieldName} = new()");
        builder.AppendLine("    {");
        builder.AppendLine($"        UnitOfWorkAttribute = {unitOfWorkAttribute},");
        builder.AppendLine($"        ApplyConventionalUnitOfWork = {aspect.ApplyConventionalUnitOfWork.ToString().ToLowerInvariant()},");
        builder.AppendLine($"        ShouldAudit = {aspect.Audit.ToString().ToLowerInvariant()},");
        builder.AppendLine($"        ShouldValidate = {aspect.Validate.ToString().ToLowerInvariant()},");
        builder.AppendLine($"        AllowAnonymous = {aspect.AllowAnonymous.ToString().ToLowerInvariant()},");
        builder.AppendLine($"        HasUseCaseAttribute = {aspect.HasUseCaseAttribute.ToString().ToLowerInvariant()},");
        builder.AppendLine($"        UseCaseDescription = {aspect.UseCaseDescriptionExpression ?? "null"},");
        builder.AppendLine($"        AuthorizeAttributes = {authorize},");
        builder.AppendLine($"        FeatureAttributes = {features}");
        builder.AppendLine("    };");
        builder.AppendLine();
    }

    private static void EmitMetadataRegistration(StringBuilder builder, MethodModel method)
    {
        var methodFieldName = GetMethodFieldName(method);
        var metadataFieldName = GetMethodMetadataFieldName(method);

        builder.AppendLine($"        {AbpTypeNames.FullyQualified.AbpMethodInterceptionMetadataProvider}.Instance.Register({methodFieldName}, {metadataFieldName});");
    }

    private static string GetMethodFieldName(MethodModel method)
    {
        if (method.Parameters.IsDefaultOrEmpty)
        {
            return $"{method.Name}Method";
        }

        var suffix = string.Join("_", method.Parameters.Select(SanitizeTypeNameForField));
        return $"{method.Name}_{suffix}_Method";
    }

    private static string GetMethodMetadataFieldName(MethodModel method)
    {
        var methodFieldName = GetMethodFieldName(method);
        return methodFieldName.EndsWith("Method", StringComparison.Ordinal)
            ? methodFieldName.Substring(0, methodFieldName.Length - "Method".Length) + "Metadata"
            : methodFieldName + "Metadata";
    }

    private static string GetInvocationMethodExpression(MethodModel method)
    {
        var methodFieldName = GetMethodFieldName(method);
        if (method.AbpReflection)
        {
            return $"new {AbpTypeNames.FullyQualified.AbpInvocationMethod}({methodFieldName}, {GetMethodMetadataFieldName(method)})";
        }

        return $"new {AbpTypeNames.FullyQualified.AbpInvocationMethod}({methodFieldName}, null)";
    }

    private static string SanitizeTypeNameForField(ParameterModel parameter)
    {
        return SanitizeTypeNameForField(parameter.TypeName);
    }

    private static string SanitizeTypeNameForField(string typeName)
    {
        return typeName
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "")
            .Replace("[", "_")
            .Replace("]", "_");
    }

    private static string EmitGetMethodParameterTypes(MethodModel method)
    {
        if (method.Parameters.IsDefaultOrEmpty)
        {
            return "global::System.Type.EmptyTypes";
        }

        return $"new global::System.Type[] {{ {string.Join(", ", method.Parameters.Select(p => $"typeof({p.TypeName})"))} }}";
    }

    private static string GetAsyncInvocationTypeName(MethodModel method, bool isTask)
    {
        var asyncTypePrefix = isTask
            ? "global::System.Threading.Tasks.Task"
            : "global::System.Threading.Tasks.ValueTask";

        if (IsGenericAsyncReturnType(method.ReturnType, out var resultType))
        {
            return $"{AbpTypeNames.FullyQualified.AbpInvocationStruct}<{asyncTypePrefix}<{resultType}>>";
        }

        return $"{AbpTypeNames.FullyQualified.AbpInvocationStruct}<{asyncTypePrefix}>";
    }
}
