using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Abp.SourceGenerators;

internal static class RegistrationEmitter
{
    public static string? EmitModulePartial(
        ModuleModel module,
        ImmutableArray<ConventionTypeModel> models,
        string? assemblyName,
        ImmutableArray<BakedInterceptorField> userInterceptors)
    {
        var generatedNs = GeneratedNamespace.Get(assemblyName);
        var ns = string.IsNullOrEmpty(module.Namespace) ? null : module.Namespace;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (ns != null)
        {
            builder.AppendLine($"namespace {ns};");
            builder.AppendLine();
        }

        var shortName = module.ModuleType.Name;
        builder.AppendLine($"public partial class {shortName}");
        builder.AppendLine("{");
        builder.AppendLine($"    public static void RegisterAssemblyByConvention({AbpTypeNames.FullyQualified.IIocManager} iocManager)");
        builder.AppendLine("    {");

        foreach (var model in models.OrderBy(m => m.ImplementationTypeName))
        {
            var lifestyle = model.IsSingleton
                ? AbpTypeNames.FullyQualified.DependencyLifeStyleSingleton
                : AbpTypeNames.FullyQualified.DependencyLifeStyleTransient;

            var implementationType = model.RequiresCompileTimeInterception
                ? $"global::{generatedNs}.{model.InterceptedTypeName}"
                : model.ImplementationTypeName;

            if (model.RequiresCompileTimeInterception)
            {
                builder.AppendLine($"        iocManager.Register<{model.ImplementationTypeName}>({lifestyle});");
            }

            if (model.ServiceInterfaces.IsDefaultOrEmpty)
            {
                if (!model.RequiresCompileTimeInterception)
                {
                    builder.AppendLine($"        iocManager.Register<{model.ImplementationTypeName}>({lifestyle});");
                }

                continue;
            }

            var registeredTypes = model.RequiresCompileTimeInterception
                ? model.ServiceInterfaces.Select(i => $"typeof({i})").ToList()
                : new List<string> { $"typeof({model.ImplementationTypeName})" }
                    .Concat(model.ServiceInterfaces.Select(i => $"typeof({i})"))
                    .ToList();

            if (registeredTypes.Count == 1)
            {
                builder.AppendLine(
                    $"        iocManager.Register<{model.ServiceInterfaces[0]}, {implementationType}>({lifestyle});");
                continue;
            }

            var serviceTypes = string.Join(", ", registeredTypes);
            var lifestyleMethod = model.IsSingleton ? "LifestyleSingleton" : "LifestyleTransient";
            builder.AppendLine("        iocManager.IocContainer.Register(");
            builder.AppendLine($"            global::Castle.MicroKernel.Registration.Component.For(new global::System.Type[] {{ {serviceTypes} }})");
            builder.AppendLine($"                .ImplementedBy(typeof({implementationType}))");
            builder.AppendLine($"                .{lifestyleMethod}());");
        }

        foreach (var interceptor in userInterceptors)
        {
            if (interceptor.TypeName != null)
            {
                builder.AppendLine(
                    $"        iocManager.Register<{interceptor.TypeName}>({AbpTypeNames.FullyQualified.DependencyLifeStyleTransient});");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    public static string EmitAssemblyInitializer(ImmutableArray<ModuleModel> modules)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Abp.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static class CompileTimeIocAssemblyInitializer");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Initialize()");
        builder.AppendLine("    {");

        foreach (var module in modules)
        {
            builder.AppendLine($"        {AbpTypeNames.FullyQualified.CompileTimeIocRegistrarRegistry}.Register(");
            builder.AppendLine($"            typeof({module.ModuleTypeName}),");
            builder.AppendLine($"            {module.ModuleTypeName}.RegisterAssemblyByConvention);");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
